image: visual studio 2017
services:
  - mssql2017
before_test:
  ps: |
      function Test-SQLConnection
      {    
          [OutputType([bool])]
          Param
          (
              [Parameter(Mandatory=$true,
                          ValueFromPipelineByPropertyName=$true,
                          Position=0)]
              $ConnectionString
          )
          try
          {
              $sqlConnection = New-Object System.Data.SqlClient.SqlConnection $ConnectionString;
              $sqlConnection.Open();
              $sqlConnection.Close();
      
              return $true;
          }
          catch
          {
              return $false;
          }
      }
      
      Test-SQLConnection "Server=(local)\SQL2017;Database=master;User ID=sa;Password=Password12!"      
test_script:
  - ps: ./test-sqlconnection.ps1
build: off
